<?php
/**
 * @file
 * Code for the humanitarianresponse assessments feature.
 */

include_once('humanitarianresponse_assessments.features.inc');


/**
 * Implements hook_form_FORM_ID_alter().
 */
function humanitarianresponse_assessments_form_assessment_node_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('entityconnect') && isset($form_state['#entityconnect_child_form'])) {
    $assessments_batch_input = $form_state['#entityconnect_child_form']->data['form_state']['input'];
    $form['field_clusters']['und']['#default_value'] = array($assessments_batch_input['field_cluster']['und']);
  }
}

/**
 * Implements hook_cron()
 */
function humanitarianresponse_assessments_cron() {
  humanitarianresponse_core_feeds_check('csv_population_types', 'http://terms.humanitarianresponse.info/population-types.csv');
}
